version: '3'
services:
  gcdm:
    image: adoptopenjdk:11-jre-hotspot
    volumes:
      - ./build/install/gcdm-local:/gcdm
      - ./sample_data:/data
    ports:
      - "16111:16111"
    command: /gcdm/bin/gcdm-local
  envoy:
    image: envoyproxy/envoy:v1.17-latest
    ports:
      - "16110:16110"
      - "9901:9901"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    links:
      - "gcdm"
